# Generated by Django 5.0.4 on 2024-04-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Favorito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ranking_favorito", models.IntegerField(default=20)),
                ("fecha_marcada", models.DateTimeField()),
                ("veces_vista", models.IntegerField(default=600)),
            ],
        ),
        migrations.CreateModel(
            name="Ingrediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_ingrediente", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="ListaDeCompras",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField()),
                ("frutas", models.TextField(max_length=3000)),
                ("verduras", models.TextField(max_length=3000)),
                ("medida", models.TextField(max_length=4000)),
                ("productos_origen_animal", models.TextField(max_length=3000)),
                ("liquidos", models.TextField(max_length=3000)),
                ("legumbres", models.TextField(max_length=3000)),
                ("cereales", models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name="PlaneacionSemanal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dia_inicio", models.DateTimeField()),
                ("dia_finalizacion", models.DateTimeField()),
                ("comida_del_dia", models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name="Receta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_receta", models.CharField(max_length=300)),
                ("calorias", models.BigIntegerField()),
                ("origen_receta", models.CharField(max_length=100)),
                ("tipo_comida", models.CharField(max_length=100)),
                ("dificultad", models.CharField(max_length=50)),
                ("pasos", models.TextField(max_length=3000)),
                (
                    "imagenes",
                    models.ImageField(blank=True, null=True, upload_to="recetas/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("nombre_completo", models.CharField(max_length=100)),
                (
                    "nombre_usuario",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("preferencias_dieteticas", models.CharField(max_length=200)),
                ("contraseña", models.CharField(max_length=16)),
                ("fecha_nacimiento", models.DateTimeField()),
                ("alergias", models.CharField(max_length=300)),
                ("tipo_cocina_favorita", models.CharField(max_length=60)),
            ],
        ),
    ]
