# Generated by Django 5.0.4 on 2024-05-13 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_alergia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking_favorito', models.IntegerField(default=20)),
                ('fecha_marcada', models.DateTimeField()),
                ('veces_vista', models.IntegerField(default=600)),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ingrediente', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ListaDeCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField()),
                ('frutas', models.TextField(max_length=3000)),
                ('verduras', models.TextField(max_length=3000)),
                ('medida', models.TextField(max_length=4000)),
                ('productos_origen_animal', models.TextField(max_length=3000)),
                ('liquidos', models.TextField(max_length=3000)),
                ('legumbres', models.TextField(max_length=3000)),
                ('cereales', models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='PlaneacionSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_inicio', models.DateTimeField()),
                ('dia_finalizacion', models.DateTimeField()),
                ('comida_del_dia', models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_receta', models.CharField(max_length=300)),
                ('calorias', models.BigIntegerField()),
                ('origen_receta', models.CharField(max_length=100)),
                ('tipo_comida', models.CharField(max_length=100)),
                ('dificultad', models.CharField(max_length=50)),
                ('pasos', models.TextField(max_length=3000)),
                ('ingredientes', models.ManyToManyField(to='app.ingrediente')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='recetas/')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='app.receta')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioComplementacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferencias_dieteticas', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('tipo_cocina_favorita', models.CharField(max_length=60)),
                ('alergias', models.ManyToManyField(to='app.alergia')),
                ('info', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
