# Generated by Django 5.0.4 on 2024-05-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='tiempo_preparacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
