# Generated by Django 5.0.4 on 2024-05-19 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_receta_tiempo_preparacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='comentarios',
        ),
        migrations.AddField(
            model_name='comentario',
            name='receta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.receta'),
        ),
    ]
