# Generated by Django 5.0.4 on 2024-05-20 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_comidasplaneacion_cena_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comidasplaneacion',
            name='cena',
            field=models.ManyToManyField(blank=True, related_name='comidasplaneacion_cena', to='app.receta'),
        ),
        migrations.AlterField(
            model_name='comidasplaneacion',
            name='colacion',
            field=models.ManyToManyField(blank=True, related_name='comidasplaneacion_colacion', to='app.receta'),
        ),
        migrations.AlterField(
            model_name='comidasplaneacion',
            name='colacion2',
            field=models.ManyToManyField(blank=True, related_name='comidasplaneacion_colacion2', to='app.receta'),
        ),
        migrations.AlterField(
            model_name='comidasplaneacion',
            name='comida',
            field=models.ManyToManyField(blank=True, related_name='comidasplaneacion_comida', to='app.receta'),
        ),
        migrations.AlterField(
            model_name='comidasplaneacion',
            name='desayuno',
            field=models.ManyToManyField(blank=True, related_name='comidasplaneacion_desayuno', to='app.receta'),
        ),
    ]
