# Generated by Django 5.0.4 on 2024-05-20 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_comidasplaneacion_cena_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comidasplaneacion',
            old_name='cena',
            new_name='cenas',
        ),
        migrations.RenameField(
            model_name='comidasplaneacion',
            old_name='colacion',
            new_name='colaciones',
        ),
        migrations.RenameField(
            model_name='comidasplaneacion',
            old_name='colacion2',
            new_name='colaciones2',
        ),
        migrations.RenameField(
            model_name='comidasplaneacion',
            old_name='comida',
            new_name='comidas',
        ),
        migrations.RenameField(
            model_name='comidasplaneacion',
            old_name='desayuno',
            new_name='desayunos',
        ),
    ]
