# Generated by Django 5.0.4 on 2024-05-20 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_cena_comidasplaneacion_cenas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comidasplaneacion',
            name='cenas',
        ),
        migrations.RemoveField(
            model_name='comidasplaneacion',
            name='colaciones',
        ),
        migrations.RemoveField(
            model_name='comidasplaneacion',
            name='colaciones2',
        ),
        migrations.RemoveField(
            model_name='comidasplaneacion',
            name='comidas',
        ),
        migrations.RemoveField(
            model_name='comidasplaneacion',
            name='desayunos',
        ),
        migrations.RemoveField(
            model_name='planeacionsemanal',
            name='comidas_del_dia',
        ),
        migrations.AddField(
            model_name='comidasplaneacion',
            name='cena',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comidasplaneacion_cena', to='app.receta'),
        ),
        migrations.AddField(
            model_name='comidasplaneacion',
            name='colacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comidasplaneacion_colacion', to='app.receta'),
        ),
        migrations.AddField(
            model_name='comidasplaneacion',
            name='colacion2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comidasplaneacion_colacion2', to='app.receta'),
        ),
        migrations.AddField(
            model_name='comidasplaneacion',
            name='comida',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comidasplaneacion_comida', to='app.receta'),
        ),
        migrations.AddField(
            model_name='comidasplaneacion',
            name='desayuno',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comidasplaneacion_desayuno', to='app.receta'),
        ),
        migrations.AddField(
            model_name='planeacionsemanal',
            name='dia1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dia1', to='app.comidasplaneacion'),
        ),
        migrations.AddField(
            model_name='planeacionsemanal',
            name='dia2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dia2', to='app.comidasplaneacion'),
        ),
        migrations.AddField(
            model_name='planeacionsemanal',
            name='dia3',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dia3', to='app.comidasplaneacion'),
        ),
        migrations.AddField(
            model_name='planeacionsemanal',
            name='dia4',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dia4', to='app.comidasplaneacion'),
        ),
        migrations.AddField(
            model_name='planeacionsemanal',
            name='dia5',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dia5', to='app.comidasplaneacion'),
        ),
        migrations.AddField(
            model_name='planeacionsemanal',
            name='dia6',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dia6', to='app.comidasplaneacion'),
        ),
        migrations.AddField(
            model_name='planeacionsemanal',
            name='dia7',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dia7', to='app.comidasplaneacion'),
        ),
    ]
