# Generated by Django 5.0.4 on 2024-05-20 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_comidasplaneacion_cenas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comidasplaneacion',
            name='cena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comidasplaneacion_cena', to='app.receta'),
        ),
        migrations.AlterField(
            model_name='comidasplaneacion',
            name='colacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comidasplaneacion_colacion', to='app.receta'),
        ),
        migrations.AlterField(
            model_name='comidasplaneacion',
            name='colacion2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comidasplaneacion_colacion2', to='app.receta'),
        ),
        migrations.AlterField(
            model_name='comidasplaneacion',
            name='comida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comidasplaneacion_comida', to='app.receta'),
        ),
        migrations.AlterField(
            model_name='comidasplaneacion',
            name='desayuno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comidasplaneacion_desayuno', to='app.receta'),
        ),
    ]
