# Generated by Django 5.0.4 on 2024-05-20 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_comidasplaneacion_cena_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comidasplaneacion',
            name='cena',
        ),
        migrations.RemoveField(
            model_name='comidasplaneacion',
            name='colacion',
        ),
        migrations.RemoveField(
            model_name='comidasplaneacion',
            name='colacion2',
        ),
        migrations.RemoveField(
            model_name='comidasplaneacion',
            name='comida',
        ),
    ]
