# Generated by Django 5.0.4 on 2024-05-20 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_comidasplaneacion_cena_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comidasplaneacion',
            name='cena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comidasplaneacion_cena', to='app.receta'),
        ),
        migrations.AddField(
            model_name='comidasplaneacion',
            name='colacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comidasplaneacion_colacion', to='app.receta'),
        ),
        migrations.AddField(
            model_name='comidasplaneacion',
            name='colacion2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comidasplaneacion_colacion2', to='app.receta'),
        ),
        migrations.AddField(
            model_name='comidasplaneacion',
            name='comida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comidasplaneacion_comida', to='app.receta'),
        ),
    ]
