# Generated by Django 5.0.4 on 2024-05-21 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_comidasplaneacion_cena_comidasplaneacion_colacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planeacionsemanal',
            name='dia_finalizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planeacionsemanal',
            name='dia_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
