# Generated by Django 5.0.4 on 2024-05-21 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_planeacionsemanal_dia_finalizacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorito',
            name='fecha_marcada',
        ),
        migrations.RemoveField(
            model_name='favorito',
            name='ranking_favorito',
        ),
        migrations.RemoveField(
            model_name='favorito',
            name='veces_vista',
        ),
        migrations.RemoveField(
            model_name='usuariocomplementacion',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='usuariocomplementacion',
            name='preferencias_dieteticas',
        ),
        migrations.RemoveField(
            model_name='usuariocomplementacion',
            name='tipo_cocina_favorita',
        ),
        migrations.AddField(
            model_name='favorito',
            name='recetas',
            field=models.ManyToManyField(to='app.receta'),
        ),
        migrations.AddField(
            model_name='favorito',
            name='usuario',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuariocomplementacion',
            name='recetas_favoritas',
            field=models.ManyToManyField(blank=True, null=True, to='app.receta'),
        ),
        migrations.AlterField(
            model_name='planeacionsemanal',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planeacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuariocomplementacion',
            name='alergias',
            field=models.ManyToManyField(blank=True, null=True, to='app.alergia'),
        ),
    ]
