# Generated by Django 5.0.4 on 2024-05-21 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_favorito_fecha_marcada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocomplementacion',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='usuariocomplementacion',
            name='lista_compras',
            field=models.ManyToManyField(blank=True, null=True, to='app.listadecompras'),
        ),
        migrations.AlterField(
            model_name='usuariocomplementacion',
            name='info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL),
        ),
    ]
