# Generated by Django 5.0.4 on 2024-05-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_usuariocomplementacion_foto_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocomplementacion',
            name='alergias',
            field=models.ManyToManyField(blank=True, to='app.alergia'),
        ),
        migrations.AlterField(
            model_name='usuariocomplementacion',
            name='lista_compras',
            field=models.ManyToManyField(blank=True, to='app.listadecompras'),
        ),
        migrations.AlterField(
            model_name='usuariocomplementacion',
            name='recetas_favoritas',
            field=models.ManyToManyField(blank=True, to='app.receta'),
        ),
    ]
