# Generated by Django 5.0.4 on 2024-05-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_usuariocomplementacion_alergias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listadecompras',
            name='cereales',
        ),
        migrations.RemoveField(
            model_name='listadecompras',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='listadecompras',
            name='frutas',
        ),
        migrations.RemoveField(
            model_name='listadecompras',
            name='legumbres',
        ),
        migrations.RemoveField(
            model_name='listadecompras',
            name='liquidos',
        ),
        migrations.RemoveField(
            model_name='listadecompras',
            name='medida',
        ),
        migrations.RemoveField(
            model_name='listadecompras',
            name='productos_origen_animal',
        ),
        migrations.RemoveField(
            model_name='listadecompras',
            name='verduras',
        ),
        migrations.AddField(
            model_name='listadecompras',
            name='ingredientes',
            field=models.ManyToManyField(blank=True, to='app.ingrediente'),
        ),
    ]
