# Generated by Django 5.0.4 on 2024-05-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_listadecompras_cereales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocomplementacion',
            name='lista_compras',
            field=models.ManyToManyField(blank=True, to='app.ingrediente'),
        ),
        migrations.DeleteModel(
            name='ListaDeCompras',
        ),
    ]
